apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common-service-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "common-service-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "common-service-chart.name" . }}
    spec:
      containers:
      - name: {{ include "common-service-chart.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
