apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-app-repo
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/<org>/app-repo.git
  ref:
    branch: develop
  secretRef:
    name: flux-system