apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-app-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Charungooa/app-repo.git
  ref:
    branch: dev  # Ensure this matches your app-repo branch
  timeout: 60s

...

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-kustom
  namespace: flux-system
spec:
  interval: 10m
  path: ./common-service-chart  # Ensure this path is correct
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-app-repo
  timeout: 3m

...