apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-kustom
  namespace: flux-system
spec:
  interval: 10m
  path: ./common-service-chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-app-repo
  # If using HelmRelease, do that instead. 
  # For inline Helm with kustomization, some advanced config might differ.
