apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-kustom
  namespace: flux-system
spec:
  interval: 10m
  path: ./common-service-chart  # Ensure this path is correct
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-app-repo
  timeout: 3m

# ...

# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: dev-kustom
#   namespace: flux-system
# spec:
#   interval: 10m
#   path: ./common-service-chart  # Ensure this path is correct
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: dev-app-repo
#     timeout: 3m

# ...